import { db } from "@/lib/db";
import { rankMissingGuestContexts, type MissingGuestCandidate } from "@/lib/missing-guest";

export async function getMissingGuestWorkspace(eventId: string, query: string) {
  const event = await db.event.findUnique({ where: { id: eventId }, select: { id: true, name: true, status: true, organizationId: true, registrations: { where: { status: "ACTIVE" }, select: { id: true, person: { select: { firstName: true, lastName: true, email: true, phone: true } }, group: { select: { name: true } }, party: { select: { name: true } }, table: { select: { name: true } }, checkIn: { select: { reversedAt: true } } } }, invitations: { where: { status: { notIn: ["CANCELLED", "DECLINED"] } }, select: { id: true, firstName: true, lastName: true, email: true, phone: true, status: true, group: { select: { name: true } } } }, groups: { select: { id: true, name: true, capacity: true, _count: { select: { registrations: { where: { status: "ACTIVE" } } } }, hosts: { select: { person: { select: { firstName: true, lastName: true } } } } } }, parties: { select: { id: true, name: true, _count: { select: { registrations: { where: { status: "ACTIVE" } } } } } }, seatingTables: { select: { id: true, name: true, capacity: true, _count: { select: { registrations: { where: { status: "ACTIVE" } } } } } } } });
  if (!event) throw new Error("This Event no longer exists.");
  const people = query.trim().length >= 2 ? await db.person.findMany({ where: { organizationId: event.organizationId, mergedIntoPersonId: null, OR: [{ firstName: { contains: query.trim(), mode: "insensitive" } }, { lastName: { contains: query.trim(), mode: "insensitive" } }] }, select: { id: true, firstName: true, lastName: true, email: true, phone: true }, take: 20 }) : [];
  const candidates: MissingGuestCandidate[] = [
    ...event.registrations.map((item) => ({ id: item.id, kind: "REGISTRATION" as const, label: `${item.person.firstName} ${item.person.lastName}`, detail: `${item.checkIn && !item.checkIn.reversedAt ? "Already checked in" : "Registered"}${item.group ? ` · ${item.group.name}` : ""}${item.party ? ` · ${item.party.name}` : ""}${item.table ? ` · ${item.table.name}` : ""}`, searchText: [item.person.firstName, item.person.lastName, item.person.email, item.person.phone, item.group?.name, item.party?.name, item.table?.name].filter(Boolean).join(" ") })),
    ...event.invitations.map((item) => ({ id: item.id, kind: "INVITATION" as const, label: `${item.firstName} ${item.lastName}`, detail: `${item.status.toLowerCase()} Invitation${item.group ? ` · ${item.group.name}` : ""}`, searchText: [item.firstName, item.lastName, item.email, item.phone, item.group?.name].filter(Boolean).join(" ") })),
    ...people.map((item) => ({ id: item.id, kind: "PERSON" as const, label: `${item.firstName} ${item.lastName}`, detail: "Existing Person without an active Registration", searchText: [item.firstName, item.lastName, item.email, item.phone].filter(Boolean).join(" ") })),
    ...event.groups.map((item) => ({ id: item.id, kind: "GROUP" as const, label: item.name, detail: `${item._count.registrations} registered${item.hosts.length ? ` · Host: ${item.hosts.map((host) => `${host.person.firstName} ${host.person.lastName}`).join(", ")}` : ""}`, searchText: `${item.name} ${item.hosts.map((host) => `${host.person.firstName} ${host.person.lastName}`).join(" ")}` })),
    ...event.parties.map((item) => ({ id: item.id, kind: "PARTY" as const, label: item.name, detail: `${item._count.registrations} people`, searchText: item.name })),
    ...event.seatingTables.map((item) => ({ id: item.id, kind: "TABLE" as const, label: item.name, detail: `${Math.max(item.capacity - item._count.registrations, 0)} seats open`, searchText: item.name, availableSeats: Math.max(item.capacity - item._count.registrations, 0) })),
  ];
  return { event: { id: event.id, name: event.name, status: event.status, organizationId: event.organizationId }, groups: event.groups.map((item) => ({ id: item.id, name: item.name, detail: item.capacity === null ? `${item._count.registrations} registered` : `${Math.max(item.capacity - item._count.registrations, 0)} spaces remaining` })), tables: event.seatingTables.map((item) => ({ id: item.id, name: item.name, detail: `${Math.max(item.capacity - item._count.registrations, 0)} seats open` })), results: rankMissingGuestContexts(query, candidates) };
}
