import { db } from "@/lib/db";
import { buildLiveBriefing } from "@/lib/live-command-center";

export async function getEventLiveCommandCenter(eventId: string) {
  const since = new Date(Date.now() - 12 * 60 * 60 * 1000);
  const event = await db.event.findUnique({ where: { id: eventId }, select: { id: true, organizationId: true, name: true, status: true, registrations: { where: { status: "ACTIVE" }, select: { id: true, source: true, tableId: true, personId: true, person: { select: { firstName: true, lastName: true } }, checkIn: { select: { reversedAt: true } }, fieldAnswers: { select: { value: true, field: { select: { key: true, label: true } } } } } }, seatingTables: { select: { id: true, name: true, capacity: true, _count: { select: { registrations: { where: { status: "ACTIVE" } } } } } }, attendanceOperations: { where: { createdAt: { gte: since } }, select: { deviceId: true, occurredAt: true, disposition: true }, orderBy: { occurredAt: "desc" }, take: 1000 }, sponsorships: { select: { sponsor: { select: { primaryContactPersonId: true } } } } } });
  if (!event) return null; const sponsorPeople = new Set(event.sponsorships.map((item) => item.sponsor.primaryContactPersonId).filter(Boolean));
  const truthy = (value: unknown) => value === true || (typeof value === "string" && /^(yes|true|vip)$/i.test(value)); const vip = (answers: Array<{ value: unknown; field: { key: string; label: string } }>) => answers.some((answer) => /\bvip\b|very important/i.test(`${answer.field.key} ${answer.field.label}`) && truthy(answer.value));
  return { event: { id: event.id, organizationId: event.organizationId, name: event.name, status: event.status }, briefing: buildLiveBriefing({ guests: event.registrations.map((item) => ({ id: item.id, name: `${item.person.firstName} ${item.person.lastName}`, arrived: Boolean(item.checkIn && !item.checkIn.reversedAt), walkIn: item.source === "WALK_IN", tableId: item.tableId, vip: vip(item.fieldAnswers), sponsorRepresentative: sponsorPeople.has(item.personId) })), tables: event.seatingTables.map((table) => ({ id: table.id, name: table.name, capacity: table.capacity, assigned: table._count.registrations })), operations: event.attendanceOperations }) };
}
