import Link from "next/link";
import { notFound } from "next/navigation";
import { LiveRefresh } from "@/components/live-refresh";
import { requireActor } from "@/lib/auth";
import { getEventLiveCommandCenter } from "@/lib/event-live-command-center";

export const dynamic = "force-dynamic";
export default async function CommandCenterPage({ params }: { params: Promise<{ eventId: string }> }) {
  const { eventId } = await params; const workspace = await getEventLiveCommandCenter(eventId); if (!workspace) notFound(); await requireActor(workspace.event.organizationId, "event:view", eventId); const { briefing } = workspace;
  return <><LiveRefresh /><Link className="back" href={`/events/${eventId}`}>← {workspace.event.name}</Link><div className="page-heading"><div><p className="eyebrow">Live Event command center</p><h1>Event-night briefing</h1><p>Canonical server totals refresh every five seconds. Offline device activity appears only after it synchronizes.</p><small className="live-note">{briefing.lastOperationAt ? `Latest server operation ${briefing.staleMinutes} minute(s) ago` : "No device operations have reached the server in the last 12 hours"}</small></div><div className="button-row"><Link className="button" href={`/events/${eventId}/check-in`}>Open check-in</Link><Link className="button secondary" href={`/events/${eventId}/check-in/missing`}>Resolve missing guest</Link></div></div><section className="metrics command-metrics"><div><strong>{briefing.metrics.arrived}</strong><span>Arrived</span></div><div><strong>{briefing.metrics.remaining}</strong><span>Remaining</span></div><div><strong>{briefing.metrics.walkIns}</strong><span>Walk-ins</span></div><div><strong>{briefing.metrics.unassignedGuests}</strong><span>Unassigned</span></div><div><strong>{briefing.metrics.tableIssues}</strong><span>Table issues</span></div></section><section className="event-section"><div className="section-heading"><h2>Priority exceptions</h2><span>{briefing.alerts.length}</span></div>{briefing.alerts.length ? <div className="command-alerts">{briefing.alerts.map((alert) => <article key={`${alert.title}:${alert.evidence}`}><span className="status">{alert.urgency}</span><div><h3>{alert.title}</h3><p><strong>Evidence:</strong> {alert.evidence}</p><p><strong>Recommended response:</strong> {alert.response}</p></div></article>)}</div> : <div className="success">No current priority exceptions.</div>}</section><section className="event-section"><div className="section-heading"><h2>Device sync evidence</h2><span>{briefing.devices.length}</span></div>{briefing.devices.length ? <div className="report-table"><div className="report-table-head"><span>Device</span><span>Last server operation</span><span>Conflicts</span><span>State</span></div>{briefing.devices.map((device) => <div key={device.deviceId}><strong>{device.deviceId}</strong><span>{device.lastSeenAt.toLocaleTimeString()}</span><span>{device.conflicts}</span><span>{device.conflicts ? "Needs attention" : "Server history clear"}</span></div>)}</div> : <div className="empty compact"><h3>No synchronized devices yet</h3><p>This view cannot see operations still queued only on an offline device.</p></div>}</section></>;
}
