import Link from "next/link";
import { notFound } from "next/navigation";
import { cancelCommitment, draftFundraisingFollowup } from "@/app/fundraising-actions";
import { CommitmentForm, FundraisingGoalForm, SponsorshipForm, SponsorshipFulfillmentForm, TransactionForm } from "@/components/fundraising-forms";
import { requireActor } from "@/lib/auth";
import { db } from "@/lib/db";
import { formatMoney, summarizeFundraising } from "@/lib/fundraising";

export const dynamic = "force-dynamic";

export default async function FundraisingPage({ params }: { params: Promise<{ eventId: string }> }) {
  const { eventId } = await params;
  const event = await db.event.findUnique({ where: { id: eventId }, include: { registrations: { where: { status: "ACTIVE" }, include: { person: true } }, groups: { orderBy: { name: "asc" } }, sponsorships: { include: { sponsor: { include: { primaryContact: true } }, group: { include: { _count: { select: { registrations: { where: { status: "ACTIVE" } } } } } }, commitment: { include: { transactions: true } } }, orderBy: { createdAt: "desc" } }, fundraisingCommitments: { include: { transactions: { orderBy: { occurredAt: "asc" } }, person: { select: { id: true, firstName: true, lastName: true, email: true, communicationOptOut: true } }, group: { select: { name: true } } }, orderBy: { committedAt: "desc" } } } });
  if (!event) notFound();
  const access = await requireActor(event.organizationId, "event:view", eventId);
  const summary = summarizeFundraising({ goalCents: event.fundraisingGoalCents, commitments: event.fundraisingCommitments });
  const money = (cents: number) => formatMoney(cents, event.currency);
  const people = Array.from(new Map(event.registrations.map(({ person }) => [person.id, { id: person.id, label: `${person.firstName} ${person.lastName}` }])).values()).sort((a, b) => a.label.localeCompare(b.label));
  const groups = event.groups.map((group) => ({ id: group.id, label: group.name }));
  const followupPeople = Array.from(new Map<string, { id: string; label: string; reason: string }>([
    ...event.fundraisingCommitments.filter((item) => item.status === "ACTIVE" && item.person && item.transactions.reduce((sum, transaction) => sum + (transaction.kind === "PAYMENT" ? transaction.amountCents : -transaction.amountCents), 0) < item.amountCents && item.person.email && !item.person.communicationOptOut).map((item) => [item.person!.id, { id: item.person!.id, label: `${item.person!.firstName} ${item.person!.lastName}`, reason: "Outstanding commitment" }] as const),
    ...event.sponsorships.filter((item) => item.fulfillmentStatus !== "COMPLETE" && item.sponsor.primaryContact?.email && !item.sponsor.primaryContact.communicationOptOut).map((item) => [item.sponsor.primaryContact!.id, { id: item.sponsor.primaryContact!.id, label: `${item.sponsor.primaryContact!.firstName} ${item.sponsor.primaryContact!.lastName}`, reason: `${item.sponsor.name} fulfillment` }] as const),
  ]).values());
  return <>
    <Link className="back" href={`/events/${eventId}`}>← {event.name}</Link>
    <div className="page-heading"><div><p className="eyebrow">Fundraising</p><h1>Fundraising ledger</h1><p>Track commitments separately from cash received so leadership always sees an honest total.</p></div><Link className="button secondary" href={`/events/${eventId}/fundraising/export`}>Export CSV</Link></div>
    <section className="metrics fundraising-metrics" aria-label="Fundraising totals"><div><strong>{summary.goalCents === null ? "—" : money(summary.goalCents)}</strong><span>Goal</span></div><div><strong>{money(summary.committedCents)}</strong><span>Committed</span></div><div><strong>{money(summary.receivedCents)}</strong><span>Received</span></div><div><strong>{money(summary.outstandingCents)}</strong><span>Outstanding</span></div><div><strong>{summary.remainingToGoalCents === null ? "—" : money(summary.remainingToGoalCents)}</strong><span>Goal remaining</span></div></section>
    {access.can("fundraising:manage") && event.status !== "ARCHIVED" && <div className="fundraising-forms"><FundraisingGoalForm eventId={eventId} goalCents={event.fundraisingGoalCents} /><CommitmentForm eventId={eventId} people={people} groups={groups} /><TransactionForm eventId={eventId} commitments={event.fundraisingCommitments.filter((item) => item.status === "ACTIVE").map((item) => ({ id: item.id, label: `${item.kind.replaceAll("_", " ")} · ${money(item.amountCents)}${item.description ? ` · ${item.description}` : ""}` }))} /><SponsorshipForm eventId={eventId} people={people} groups={groups} /></div>}
    <section className="event-section"><div className="section-heading"><h2>Commitments</h2><span>{event.fundraisingCommitments.length}</span></div>{event.fundraisingCommitments.length === 0 ? <div className="empty compact"><h3>No fundraising recorded</h3><p>Add a Donation, Pledge, Sponsorship, or ticket commitment to begin.</p></div> : <div className="report-table fundraising-table"><div className="report-table-head"><span>Type / attribution</span><span>Amount</span><span>Received</span><span>Outstanding</span></div>{event.fundraisingCommitments.map((item) => { const received = item.transactions.reduce((sum, transaction) => sum + (transaction.kind === "PAYMENT" ? transaction.amountCents : -transaction.amountCents), 0); return <div key={item.id}><strong>{item.kind.replaceAll("_", " ")} · {item.status}<small>{[item.description, item.person ? `${item.person.firstName} ${item.person.lastName}` : "", item.group?.name].filter(Boolean).join(" · ")}</small></strong><span>{money(item.amountCents)}</span><span>{money(received)}</span><span>{money(Math.max(item.amountCents - received, 0))}{access.can("fundraising:manage") && item.status === "ACTIVE" && received === 0 && <form action={cancelCommitment}><input type="hidden" name="eventId" value={eventId} /><input type="hidden" name="commitmentId" value={item.id} /><button type="submit">Cancel</button></form>}</span></div>; })}</div>}</section>
    <section className="event-section"><div className="section-heading"><h2>Sponsor fulfillment</h2><span>{event.sponsorships.length}</span></div>{event.sponsorships.length === 0 ? <div className="empty compact"><h3>No sponsors yet</h3><p>Add a sponsor above to track money, guests, benefits, and recognition together.</p></div> : <div className="card-grid">{event.sponsorships.map((item) => { const received = item.commitment.transactions.reduce((sum, transaction) => sum + (transaction.kind === "PAYMENT" ? transaction.amountCents : -transaction.amountCents), 0); const guests = item.group?._count.registrations ?? 0; return <article className="form-card" key={item.id}><h3>{item.sponsor.name} · {item.level}</h3><p>{money(received)} received of {money(item.commitment.amountCents)} · {guests} of {item.guestAllotment} sponsor guests</p>{item.sponsor.primaryContact && <p>Contact: {item.sponsor.primaryContact.firstName} {item.sponsor.primaryContact.lastName}</p>}{item.benefits && <p><strong>Benefits:</strong> {item.benefits}</p>}{item.recognitionNeeds && <p><strong>Recognition:</strong> {item.recognitionNeeds}</p>}{access.can("fundraising:manage") && <SponsorshipFulfillmentForm eventId={eventId} sponsorshipId={item.id} status={item.fulfillmentStatus} notes={item.fulfillmentNotes ?? ""} />}</article>; })}</div>}</section>
    {access.can("fundraising:manage") && event.status !== "ARCHIVED" && <section className="event-section"><div className="section-heading"><div><h2>Approved follow-up</h2><p>Choose only the outstanding donors or sponsor contacts who need this message. Saving creates a reviewable Campaign; it never sends immediately.</p></div><Link href={`/events/${eventId}/communications`}>Review campaigns</Link></div>{followupPeople.length === 0 ? <div className="empty compact"><p>No reachable contacts currently need follow-up.</p></div> : <form action={draftFundraisingFollowup} className="form-card"><input type="hidden" name="eventId" value={eventId} /><fieldset><legend>Recipients</legend>{followupPeople.map((person) => <label key={person.id} className="checkbox-row"><input type="checkbox" name="personId" value={person.id} /><span><strong>{person.label}</strong><small>{person.reason}</small></span></label>)}</fieldset><label>Subject<input name="subject" defaultValue={`A quick follow-up for ${event.name}`} required /></label><label>Message<textarea name="body" rows={6} defaultValue={`Hi {{firstName}},\n\nWe’re following up on an outstanding item for ${event.name}. Please reply if we can help complete it.\n\nThank you!`} required /></label><label>Schedule (optional)<input type="datetime-local" name="scheduledFor" /></label><button type="submit">Create reviewed campaign</button></form>}</section>}
  </>;
}
