import { HostGuestForm } from "@/components/host-guest-form";
import { db } from "@/lib/db";
import { assertHostScope, hashHostToken, isHostTokenActive, remainingSeats } from "@/lib/host-access";
export default async function HostPortalPage({ params, searchParams }: { params: Promise<{ token: string }>; searchParams: Promise<{ registered?: string }> }) {
  const { token } = await params;
  const access = await db.hostAccessToken.findUnique({ where: { tokenHash: hashHostToken(token) }, include: { eventHost: { include: { person: true, event: true, group: { include: { registrations: { include: { person: true }, orderBy: { registeredAt: "desc" } } } } } } } });
  if (!access || !isHostTokenActive(access)) return <div className="narrow"><div className="empty"><div className="empty-icon">◇</div><h1>This host link is unavailable</h1><p>It may have expired or been replaced. Ask event staff for a new link.</p></div></div>;
  const { eventHost } = access; try { assertHostScope(eventHost, eventHost.group); } catch { return <div className="narrow"><div className="alert">This host link is unavailable. Ask event staff for a new link.</div></div>; }
  const occupied = eventHost.group.registrations.length; const remaining = remainingSeats(eventHost.group.capacity, occupied); const guests = eventHost.group.registrations.filter((registration) => registration.personId !== eventHost.personId); const { registered } = await searchParams;
  return <><div className="portal-hero"><p className="eyebrow">Host portal</p><h1>Hi, {eventHost.person.firstName}</h1><p>{eventHost.event.name} · {eventHost.group.name}</p></div>{registered && <div className="success" role="status">Guest added successfully.</div>}<section className="metrics"><div><strong>{occupied}</strong><span>Group registered</span></div><div><strong>{remaining ?? "—"}</strong><span>Seats remaining</span></div></section>{remaining !== null && remaining <= 2 && remaining > 0 && <div className="capacity-warning">Only {remaining} {remaining === 1 ? "seat" : "seats"} left in your group.</div>}{remaining === 0 && <div className="capacity-warning full">Your group is full. Contact event staff if you need another seat.</div>}<div className="portal-grid"><section><div className="section-heading"><h2>Your guests</h2><span>{guests.length}</span></div>{guests.length === 0 ? <div className="empty compact"><h3>No guests yet</h3><p>Add your first guest using the form.</p></div> : <div className="registrants">{guests.map(({ id, person }) => <article key={id}><div className="avatar">{person.firstName[0]}{person.lastName[0]}</div><div><strong>{person.firstName} {person.lastName}</strong><p>{person.email ?? person.phone}</p></div><span>Registered</span></article>)}</div>}</section><section><h2>Add a guest</h2><HostGuestForm token={token} disabled={remaining === 0} /></section></div></>;
}
