"use server";
import { Prisma, RecommendationStatus } from "@prisma/client";
import { revalidatePath } from "next/cache";
import { requireActor } from "@/lib/auth";
import { db } from "@/lib/db";
import { getDuplicateQueue } from "@/lib/event-duplicate-queue";
import { mergePeople } from "@/lib/person-resolution";

export async function decideDuplicatePair(formData: FormData) {
  const eventId = String(formData.get("eventId") ?? ""); const pairKey = String(formData.get("pairKey") ?? ""); const fingerprint = String(formData.get("fingerprint") ?? ""); const choice = String(formData.get("choice") ?? ""); const sourcePersonId = String(formData.get("sourcePersonId") ?? ""); const targetPersonId = String(formData.get("targetPersonId") ?? "");
  if (!eventId || !pairKey || fingerprint.length !== 64 || !["MERGE", "USE_EXISTING", "KEEP_SEPARATE", "ASK_GUEST", "REVIEW_LATER"].includes(choice)) throw new Error("Review the duplicate decision.");
  const workspace = await getDuplicateQueue(eventId); if (!workspace) throw new Error("This Event no longer exists."); const pair = workspace.pairs.find((item) => item.key === pairKey && item.fingerprint === fingerprint); if (!pair) throw new Error("Person details changed. Review this pair again."); const { user } = await requireActor(workspace.event.organizationId, "person:resolve", eventId);
  if (choice === "MERGE" || choice === "USE_EXISTING") { if (![pair.first.id, pair.second.id].includes(sourcePersonId) || ![pair.first.id, pair.second.id].includes(targetPersonId) || sourcePersonId === targetPersonId) throw new Error("Choose which Person record to keep."); await mergePeople({ organizationId: workspace.event.organizationId, eventId, actorId: user.id, sourcePersonId, targetPersonId, reason: choice === "USE_EXISTING" ? "Duplicate queue: use existing canonical Person" : "Duplicate queue: confirmed merge" }); }
  const status = choice === "REVIEW_LATER" ? RecommendationStatus.SNOOZED : choice === "ASK_GUEST" ? RecommendationStatus.APPROVED : RecommendationStatus.EXECUTED; const snoozedUntil = choice === "REVIEW_LATER" ? new Date(Date.now() + 7 * 86_400_000) : null;
  await db.$transaction(async (tx) => { const record = await tx.recommendation.upsert({ where: { eventId_dedupeKey_sourceFingerprint: { eventId, dedupeKey: pair.key, sourceFingerprint: pair.fingerprint } }, create: { organizationId: workspace.event.organizationId, eventId, kind: "PERSON_DUPLICATE", status, title: `Review ${pair.first.firstName} ${pair.first.lastName} and ${pair.second.firstName} ${pair.second.lastName}`, why: "Identity evidence suggests these records may describe the same Person.", evidence: { evidence: pair.evidence, consequences: pair.consequences } as Prisma.InputJsonValue, proposedAction: { type: choice, sourcePersonId, targetPersonId } as Prisma.InputJsonValue, expectedImpact: choice === "ASK_GUEST" ? "Staff will confirm identity before any merge." : "Resolved pair is suppressed until material Person data changes.", confidence: pair.confidence, dedupeKey: pair.key, sourceFingerprint: pair.fingerprint, snoozedUntil, decidedById: user.id, decidedAt: new Date(), executedAt: status === "EXECUTED" ? new Date() : null }, update: { status, snoozedUntil, decidedById: user.id, decidedAt: new Date(), executedAt: status === "EXECUTED" ? new Date() : null } }); await tx.auditLog.create({ data: { organizationId: workspace.event.organizationId, eventId, actorId: user.id, action: `person_duplicate.${choice.toLowerCase()}`, entityType: "Recommendation", entityId: record.id, newState: JSON.stringify({ pairKey, fingerprint, choice, sourcePersonId, targetPersonId }) } }); });
  revalidatePath(`/events/${eventId}/registrations/duplicates`); revalidatePath(`/events/${eventId}/registrations`);
}
