"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireActor } from "@/lib/auth";
import { eventFormValues } from "@/lib/event-datetime";
import { proposeEventBuild, type EventBuildProposal } from "@/lib/event-builder";
import { eventSchema } from "@/lib/validation";
import { withSerializableRetry } from "@/lib/transactions";

export type EventBuilderState = { error?: string; proposal?: EventBuildProposal; description?: string; fields?: Record<string, string[]> };
export async function draftEventProposal(_: EventBuilderState, formData: FormData): Promise<EventBuilderState> { const description = String(formData.get("description") ?? "").trim(); if (description.length < 10) return { error: "Describe the Event in at least a short sentence.", description }; return { description, proposal: proposeEventBuild(description) }; }

const optionsSchema = z.object({ organizationId: z.string().min(1), description: z.string().min(10), tableCount: z.coerce.number().int().min(1).max(500).optional(), seatsPerTable: z.coerce.number().int().min(1).max(1000).optional(), createTables: z.coerce.boolean().optional().default(false), createHostGroups: z.coerce.boolean().optional().default(false), createQuestions: z.coerce.boolean().optional().default(false) });
export async function approveEventProposal(_: EventBuilderState, formData: FormData): Promise<EventBuilderState> {
  const raw = Object.fromEntries(formData); for (const key of ["tableCount", "seatsPerTable"]) if (raw[key] === "") delete raw[key]; const options = optionsSchema.safeParse(raw); const event = eventSchema.safeParse(eventFormValues(formData)); if (!options.success || !event.success) return { error: "Review the required Event details and selected changes.", description: String(formData.get("description") ?? ""), proposal: proposeEventBuild(String(formData.get("description") ?? "")), fields: event.success ? undefined : event.error.flatten().fieldErrors };
  if ((options.data.createTables || options.data.createHostGroups) && (!options.data.tableCount || !options.data.seatsPerTable)) return { error: "Enter the Table count and seats per Table for the selected layout.", description: options.data.description, proposal: proposeEventBuild(options.data.description) };
  try { const { user } = await requireActor(options.data.organizationId, "event:create"); const created = await withSerializableRetry(async (tx) => { const built = await tx.event.create({ data: { organizationId: options.data.organizationId, ...event.data } }); const count = options.data.tableCount ?? 0; const seats = options.data.seatsPerTable ?? 0; if (options.data.createTables) await tx.seatingTable.createMany({ data: Array.from({ length: count }, (_, index) => ({ organizationId: options.data.organizationId, eventId: built.id, name: `Table ${index + 1}`, capacity: seats })) }); if (options.data.createHostGroups) await tx.group.createMany({ data: Array.from({ length: count }, (_, index) => ({ organizationId: options.data.organizationId, eventId: built.id, name: `Table ${index + 1} Group`, capacity: seats })) }); if (options.data.createQuestions) await tx.eventRegistrationField.createMany({ data: [{ organizationId: options.data.organizationId, eventId: built.id, key: "dietary_needs", label: "Dietary needs", type: "TEXTAREA", sortOrder: 0 }, { organizationId: options.data.organizationId, eventId: built.id, key: "accessibility_needs", label: "Accessibility or seating accommodations", type: "TEXTAREA", sortOrder: 1 }] }); await tx.auditLog.create({ data: { organizationId: options.data.organizationId, eventId: built.id, actorId: user.id, action: "event.assistant_built", entityType: "Event", entityId: built.id, newState: JSON.stringify({ event: built, description: options.data.description, applied: { tables: options.data.createTables ? count : 0, hostGroups: options.data.createHostGroups ? count : 0, registrationQuestions: options.data.createQuestions ? 2 : 0 }, communicationPlan: proposeEventBuild(options.data.description).communicationPlan }) } }); return built; }); revalidatePath("/events"); redirect(`/events/${created.id}`); } catch (error) { if ((error as { digest?: string }).digest?.startsWith("NEXT_REDIRECT")) throw error; return { error: error instanceof Error ? error.message : "The reviewed Event could not be created.", description: options.data.description, proposal: proposeEventBuild(options.data.description) }; }
}
