import Link from "next/link";
import { notFound } from "next/navigation";
import { MoveForm, PartyForm, TableForm } from "@/components/seating-forms";
import { requireActor } from "@/lib/auth";
import { db } from "@/lib/db";
import { tableCapacity } from "@/lib/seating";

export default async function SeatingPage({ params, searchParams }: { params: Promise<{ eventId: string }>; searchParams: Promise<{ tableCreated?: string; partyCreated?: string; moved?: string }> }) {
  const { eventId } = await params;
  const event = await db.event.findUnique({ where: { id: eventId }, include: { seatingTables: { include: { registrations: { include: { person: true, group: true, party: true }, orderBy: { person: { lastName: "asc" } } } }, orderBy: { name: "asc" } }, registrations: { include: { person: true, group: true, party: true }, orderBy: [{ person: { lastName: "asc" } }, { person: { firstName: "asc" } }] }, groups: { orderBy: { name: "asc" } }, parties: { include: { _count: { select: { registrations: true } } }, orderBy: { name: "asc" } } } });
  if (!event) notFound(); await requireActor(event.organizationId, "seating:manage", eventId); const status = await searchParams;
  const tableOptions = event.seatingTables.map((table) => ({ id: table.id, name: table.name }));
  const registrationOptions = event.registrations.map((registration) => ({ id: registration.id, name: `${registration.person.firstName} ${registration.person.lastName}`, detail: registration.group?.name ?? "No group" }));
  const unassigned = event.registrations.filter(({ tableId }) => tableId === null);
  return <><Link className="back" href={`/events/${eventId}`}>← {event.name}</Link><div className="page-heading"><div><p className="eyebrow">Tables & seating</p><h1>Arrange the room</h1><p>Seat individuals, groups, or parties. Capacity checks happen before every move.</p></div></div>{(status.tableCreated || status.partyCreated || status.moved) && <div className="success" role="status">{status.tableCreated ? "Table created." : status.partyCreated ? "Party created." : "Seating updated."}</div>}
    <section className="seating-summary"><div><strong>{event.seatingTables.length}</strong><span>Tables</span></div><div><strong>{event.registrations.length - unassigned.length}</strong><span>Seated</span></div><div><strong>{unassigned.length}</strong><span>Unassigned</span></div></section>
    {event.seatingTables.length === 0 ? <div className="empty compact"><h2>No tables yet</h2><p>Create the first table to begin arranging this event.</p></div> : <section className="table-grid">{event.seatingTables.map((table) => { const capacity = tableCapacity(table.capacity, table.registrations.length); return <article className={`table-card ${capacity.overBy ? "over-capacity" : ""}`} key={table.id}><div className="table-card-head"><div><h2>{table.name}</h2><p>{table.notes || "No notes"}</p></div><div className="seat-count"><strong>{table.registrations.length}/{table.capacity}</strong><span>{capacity.overBy ? `${capacity.overBy} over` : `${capacity.remaining} left`}</span></div></div>{table.registrations.length === 0 ? <p className="table-empty">No one is seated here.</p> : <div className="seat-list">{table.registrations.map(({ id, person, group, party }) => <div key={id}><span>{person.firstName} {person.lastName}</span><small>{party?.name ?? group?.name ?? "Individual"}</small></div>)}</div>}</article>; })}</section>}
    {unassigned.length > 0 && <section className="event-section"><div className="section-heading"><h2>Unassigned guests</h2><span>{unassigned.length}</span></div><div className="unassigned-list">{unassigned.map(({ id, person, group }) => <span key={id}>{person.firstName} {person.lastName}<small>{group?.name ?? "No group"}</small></span>)}</div></section>}
    <section className="seating-tools"><div><h2>Move seating</h2>{event.seatingTables.length === 0 ? <p className="form-hint">Create a table before assigning guests.</p> : <div className="move-grid"><MoveForm eventId={eventId} sourceType="registration" title="Move a person" sources={registrationOptions} tables={tableOptions} /><MoveForm eventId={eventId} sourceType="group" title="Move a group" sources={event.groups.map(({ id, name }) => ({ id, name }))} tables={tableOptions} /><MoveForm eventId={eventId} sourceType="party" title="Move a party" sources={event.parties.map(({ id, name, _count }) => ({ id, name: `${name} (${_count.registrations})` }))} tables={tableOptions} /></div>}</div><div><TableForm eventId={eventId} /><PartyForm eventId={eventId} registrations={registrationOptions} /></div></section>
  </>;
}
